---

 - include_vars: "inv/aws/vars.yaml"

 - name: Install unzip
   yum: 
    name: unzip
    state: latest
   become: yes
   become_user: root

 - name: Download JDK
   yum: 
    name: java-1.8.0-openjdk
    state: latest
   become: yes
   become_user: root

 - name: Create tomcat group if not present
   group:
    name="{{ tomcat_group }}"
    state=present
   become: yes
   become_user: root

 - name: Add users if not present
   user:
    name="{{ tomcat_user }}"
    group="{{ tomcat_group }}"
    shell="/bin/bash"
   become: yes
   become_user: root

 - name: Download tomcat from apache
   get_url: url="{{tomcat_url}}" dest=/tmp/ force=no

 - name: Unzip tomcat
   unarchive:
    src: "/tmp/apache-tomcat-{{tomcat_version}}.zip"
    dest: /opt/
    copy: no
   become: yes
   become_user: root

 - name: Rename tomcat folder
   command: mv  "apache-tomcat-{{tomcat_version}}" apache-tomcat
   args:
     chdir: /opt/
   become: yes
   become_user: root

 - name: Change tomcat folder user permissions
   file:
    path: "/opt/apache-tomcat"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    recurse: yes
    state: directory
   become: yes
   become_user: root

 - name: Make tomcat executable
   command: /bin/sh -c 'chmod 755 /opt/apache-tomcat/bin/*.sh'
   become: yes
   become_user: root

 - template:
    src: templates/tomcat.j2
    dest: /etc/init.d/tomcat
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 775
   become: yes
   become_user: root

 - name: Register tomcat
   command: chkconfig --add tomcat
   become: yes
   become_user: root

 # - name: Replace the server.xml to enable ssl
 #   command: cp /tmp/server.xml "/opt/apache-tomcat/conf/server.xml"
 #   become: yes
 #   become_user: tomcat

 - name: Delete tomcat examples folder
   file:
     path: "/opt/apache-tomcat/webapps/examples"
     state: absent
   become: yes
   become_user: root

 - name: Make conf folder readable only from the tomcat user
   file:
     path: "/opt/apache-tomcat/conf"
     state: directory
     recurse: true
     mode: 4440
   become: yes
   become_user: root

 - name: Delete old webapps
   shell: rm -rf *
   args:
     chdir: /opt/apache-tomcat/webapps/
   become: yes
   become_user: root

 - name: Start tomcat
   command: service tomcat start
   become: yes
   become_user: root

 - name: Wait for tomcat to start
   wait_for:
     path: /opt/apache-tomcat/logs/catalina.out
     search_regex: Server startup   
   become: yes
   become_user: tomcat