---

 - include_vars: "inv/aws/vars.yaml"

 - name: Install unzip
   yum: 
    name: unzip
    state: latest
   become: yes
   become_user: root

 - name: Download JDK
   yum: 
    name: java-1.8.0-openjdk
    state: latest
   become: yes
   become_user: root

 - name: Create Tomcat group if not present
   group:
    name="{{ tomcat_group }}"
    state=present
   become: yes
   become_user: root

 - name: Add users if not present
   user:
    name="{{ tomcat_user }}"
    group="{{ tomcat_group }}"
    shell="/bin/bash"
   become: yes
   become_user: root

 - name: Download Tomcat from Apache
   get_url: url="https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_version}}/src/apache-tomcat-{{tomcat_version}}-src.zip" dest=/tmp/ force=no

 - name: Unzip Tomcat
   command: unzip -o "/tmp/apache-tomcat-{{tomcat_version}}-src.zip" -d /var/
   become: yes
   become_user: root

 - name: Rename Tomcat folder
   command: mv  "apache-tomcat-{{tomcat_version}}-src" apache-tomcat
   args:
     chdir: /var/
   become: yes
   become_user: root

 - name: Change tomcat folder user permissions
   file:
    path: "/var/apache-tomcat"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    recurse: yes
    state: directory
   become: yes
   become_user: root

 - name: Make Tomcat executable
   command: /bin/sh -c 'chmod 755 /var/apache-tomcat/bin/*.sh'
   become: yes
   become_user: root

 - template:
    src: templates/tomcat.j2
    dest: /etc/init.d/tomcat
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 775
   become: yes
   become_user: root

 # - name: Make tomcat service script executable
 #   command: chmod 755 /tmp/tomcat
 #   become: yes
 #   become_user: root

 # - name: Move Tomcat startup script to init.d
 #   command: cp /tmp/tomcat  /etc/init.d/
 #   become: yes
 #   become_user: root

 - name: Register Tomcat
   command: chkconfig --add tomcat
   become: yes
   become_user: root

 # - name: Replace the server.xml to enable ssl
 #   command: cp /tmp/server.xml "/var/apache-tomcat/conf/server.xml"
 #   become: yes
 #   become_user: tomcat

 - name: Delete Tomcat Examples folder
   file:
     path: "/var/apache-tomcat/webapps/examples"
     state: absent
   become: yes
   become_user: root

 - name: Start Tomcat
   command: service tomcat start
   become: yes
   become_user: root

 - name: Wait for Tomcat to start
   shell: curl --head http://localhost:8080
   register: result
   until: result.stdout.find("200 OK") != -1
   retries: 10
   delay: 30